server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#server:
# port: 9000
#
#spring:
# jpa:
#  show-sql: true
#  hibernate:
#   ddl-auto: update
# datasource:
#  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cards
#  username: root
#  password: root
#  driver-class-name: com.mysql.cj.jdbc.Driver
